# Generated by Django 5.0.6 on 2024-07-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_arbitro_jugador_presidente_remove_result_match_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitro",
            name="federacion",
            field=models.CharField(default="", max_length=100),
            preserve_default=False,
        ),
    ]
